name: "Bing Crawler"
on: 
  schedule:
    - cron: '0/10 * * * *'
  push:
    
jobs:
  job_1:
    name: Python Crawler
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: biechuyangwang-patch-1
    - name: Clear Previous
      run: |
        rm -f -- *.jpg
        rm -f -- *.png
    - name: Setup Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install Dependence
      run: pip install -r requirements.txt
    - name: Run main.py
      run: python main.py
    - name: List
      run: ls
    - name: Upload to this repo
      run: |
        git config --global user.name "biechuyangwang" # 改成Github账号用户名
        git config --global user.email "1101049446@qq.com" # 改成GitHub账号的邮箱
        git add "*.jpg" "*.png" && echo "Git Added"
        git commit -m 'upload main result' && echo "Git Committed"
        git push -u origin biechuyangwang-patch-2 && echo "Git Pushed Origin"
    - name: Failure test
      if: failure()
      run: |
        ls
        echo "Error on running!!"
